/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_2 (
    input clk,
    input rst,
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] boole
  );
  
  
  
  
  integer i;
  
  integer choice;
  
  always @* begin
    boole = 8'h00;
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      if (a[(i)*1+0-:1] == 1'h0 && b[(i)*1+0-:1] == 1'h0) begin
        choice = 2'h0;
      end else begin
        if (a[(i)*1+0-:1] == 1'h1 && b[(i)*1+0-:1] == 1'h0) begin
          choice = 2'h2;
        end else begin
          if (a[(i)*1+0-:1] == 1'h0 && b[(i)*1+0-:1] == 1'h1) begin
            choice = 2'h1;
          end else begin
            if (a[(i)*1+0-:1] == 1'h1 && b[(i)*1+0-:1] == 1'h1) begin
              choice = 2'h3;
            end
          end
        end
      end
      if (choice == 2'h0) begin
        boole[(i)*1+0-:1] = alufn[0+0-:1];
      end else begin
        if (choice == 2'h2) begin
          boole[(i)*1+0-:1] = alufn[1+0-:1];
        end else begin
          if (choice == 2'h1) begin
            boole[(i)*1+0-:1] = alufn[2+0-:1];
          end else begin
            if (choice == 2'h3) begin
              boole[(i)*1+0-:1] = alufn[3+0-:1];
            end
          end
        end
      end
    end
  end
endmodule
