/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_5 (
    input clk,
    input rst,
    input [7:0] a,
    input [4:0] b,
    input [5:0] alufn,
    output reg [7:0] sum
  );
  
  
  
  
  always @* begin
    sum = 8'h00;
    if (alufn[0+1-:2] == 2'h0) begin
      sum = a << b;
    end else begin
      if (alufn[0+1-:2] == 2'h2) begin
        sum = a >> b;
      end else begin
        if (alufn[0+1-:2] == 2'h3) begin
          sum = $signed(a) >>> b;
        end
      end
    end
  end
endmodule
