/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_6 (
    input clk,
    input rst,
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg out
  );
  
  
  
  
  always @* begin
    out = 1'h0;
    if (alufn[1+1-:2] == 2'h1) begin
      out = z;
    end
    if (alufn[1+1-:2] == 2'h2) begin
      out = n ^ v;
    end
    if (alufn[1+1-:2] == 2'h3) begin
      out = z | (n ^ v);
    end
  end
endmodule
